### ISSUE TITLE
Immich kiosk logo page sometimes

### ISSUE THREAD

**Issue by carlosjfcasero** [damongolding/immich-kiosk#455]
**Describe the bug**
Sometimes image is not shown. Log is full of lines like following:
```
immich-kiosk  | 11:33:33 ERRO rendering view err="context canceled"
immich-kiosk  | 11:33:34 ERRO rendering view err="context canceled"
immich-kiosk  | 12:03:40 ERRO rendering view err="context canceled"
immich-kiosk  | 12:33:55 ERRO rendering view err="context canceled"
immich-kiosk  | 12:33:56 ERRO rendering view err="context canceled"
immich-kiosk  | 13:03:59 ERRO rendering view err="context canceled"
immich-kiosk  | 13:34:11 ERRO rendering view err="context canceled"
immich-kiosk  | 13:34:11 ERRO rendering view err="context canceled"
immich-kiosk  | 14:04:25 ERRO rendering view err="context canceled"
immich-kiosk  | 14:34:37 ERRO rendering view err="context canceled"
immich-kiosk  | 14:34:38 ERRO rendering view err="context canceled"
immich-kiosk  | 15:04:55 ERRO rendering view err="context canceled"
immich-kiosk  | 15:34:59 ERRO rendering view err="context canceled"
immich-kiosk  | 16:05:11 ERRO rendering view err="context canceled"
immich-kiosk  | 16:35:24 ERRO rendering view err="context canceled"
immich-kiosk  | 17:02:13 ERRO rendering view err="context canceled"
immich-kiosk  | 17:07:35 ERRO rendering view err="context canceled"
immich-kiosk  | 17:18:24 ERRO rendering view err="context canceled"
```

**To Reproduce**
1. Access to kiosk URL (time refresh by default is 30 minutes, which coincides with time between errors above)
2. Sometimes image is not shown. Sometimes it is (it happens specially in my Google Nest Hub)
3. If I get the Immich-kiosk logo page (see screenshot below) and I refresh, a picture is taken correctly (but in Google Nest hub it's annoying having to refresh manually each time it fails)

**Expected behavior**
All images are shown

**Screenshots**

![Image](https://github.com/user-attachments/assets/c682d9ee-8a86-4ba4-8474-41526f49bc11)

**Your Kiosk version**
Version 0.21.4

**Your Kiosk installation**
- Docker

**Your Kiosk ENV or config file**
```
immich_api_key: "XXX"
immich_url: "XXX"

show_time: true # true or false
show_date: true # true or false

refresh: 1800 # in seconds

album:
  - 5e1b3ba5-c111-4ad5-8fc2-5b170c776757 # 2015
  - fa5495c0-720e-45ff-b8a0-1c0490b12e43 # 2016
  - d1522dc2-2392-45c4-8efe-adcdee2e266f # 2017
  - 38bee94e-86d4-4618-831a-83dd7fb0bde1 # 2018
  - 3fbb2cc4-5785-426c-8373-fbae6b3c954b # 2019
  - c9638476-c5a1-4cec-9f77-e44c1735654b # 2020
  - 36d9a7d8-6e28-4495-b381-959df7bc02cc # 2021
  - 5b04097d-43fe-41ec-a630-6f49e86eccad # 2022
  - feb234ed-7f53-44c7-bb19-34511dd69e2f # 2023
  - 682109e0-f2a6-4ed1-9a70-9b0ca11ffe5f # 2024
  - f7b4ec9a-da3c-45ca-9f55-5da0a2615a4f # 2025

#person:
#  - all

excluded_people:
  - 6df33197-2e47-443e-9833-39b22b486712

#person: # ID(s) of person or people to display
#  - "e1f6a8c3-8d87-4771-8a8c-9a055ff1476a" #Paula
#  - "cb59f30d-759f-482e-bba0-6279143fa4cf" #Carlos
#  - "538c21c4-9fde-441e-9dc6-bd6413341e0d" #Eva
#  - "4a025408-5f40-45c7-931c-33f76a9943f5" #Carlitos

transition: cross-fade # cross-fade, fade or none

show_progress: true # display a progress bar

# Image METADATA
show_image_time: true # true or false
show_image_date: true # true or false
show_image_location: true
```

**Any parms passed to the URL used to access Kiosk**
- NA

**Desktop:**
 - It happens in Google Nest Hub, Mac, and Linux (I guess it's not related to client)

**Comment by damongolding** [comment]
That is very odd. That error normally happens when a view/image is being created and streamed to the client and the process is broken/interrupted. It only really happens when the page is refreshed while Kiosk is doing the above. 

If you set the refresh time to a lower number don't see the same? Say 60 seconds?

**Comment by carlosjfcasero** [comment]
I checked devtools in browser and saw this (last ABORTED call):

![Image](https://github.com/user-attachments/assets/37eec36b-0d46-4aa5-91c4-01928f1de86a)

Does it mean something?

**Comment by damongolding** [comment]
Haven’t seen that error in quite some time. It’s normally linked to expire headers. I’ll have a look if I set those. If not I will add them to the next patch when I’m back from vacation.

**Comment by damongolding** [comment]
I just released v0.21.5 which adds the cache headers to all Kiosk responses. When you get a moment could you update and see if this fixes your issue?

**Comment by carlosjfcasero** [comment]
Hi @damongolding 
I updated my server to version 0.21.5 and the underlying problem has changed (I think) but the user experience is the same:

![Image](https://github.com/user-attachments/assets/756779e0-5648-4226-a345-fecaa46c5829)

![Image](https://github.com/user-attachments/assets/cc9bd2e2-143c-4ffc-b30d-6d79cdf2e2a9)

**Comment by damongolding** [comment]
Hmmm could you try having a small refresh time? You can add this to the end your url`?refresh=10`.

Could you also try enabling the time/clock from the server `?refresh=10&show_time=true&clock_source=server`. With this I want to see if that http request is also gets cancelled. 

Another thing to try is for change the response protocol but that's something I need to do.

**Comment by carlosjfcasero** [comment]
Adding did not solve the problem, the first call is still cancelled:

![Image](https://github.com/user-attachments/assets/2301cdb9-45c1-416a-a36e-8b59f1ea487d)

The next calls did work, but I'm not comfortable with a 10s period.

What I noticed is following scenario:

1. Open incognito window in browser
2. Go to my Immich-kiosk URL
3. I get cancelled issue and no picture is displayed
4. Next "new" call is successful and correspondent picture is shown
5. Close incognito
6. Open another incognito
7. Go to my Immich-kiosk URL
8. First picture is retrieved successfully

Maybe is a problem of timeouts (server taking too much time in giving response)?

**Comment by damongolding** [comment]
The 10s refresh was just to test a theory. 

It does seem like the server is taking too long on first request. This is typically the longest response call as Kiosk is getting and caching data. It would also explain why you are seeing this after 30 min as the cache will be invalid by then so Kiosk will refresh it. 

What we can do is increase the timeout. You can do this using https://docs.immichkiosk.app/configuration/additional-options/#http-timeout. The default is 20s so maybe try 60 or you can use 0 to have no timeout. 

Is the hardware you're running Kiosk on limited or are you experiencing slow network speeds from the server?

**Comment by damongolding** [comment]
This would explain the context errors you are seeing too. The browser/frontend is closing the connection so Kiosk cancels the context/rendering.

**Comment by carlosjfcasero** [comment]
I will check ASAP increasing the timeout and will let you know. I'm not experiencing network issues but it does seem is a timeout error. My hardware hasn't changed but I feel my server slower in general, so it makes sense to me the timeouts issue

**Comment by carlosjfcasero** [comment]
Sorry for my late response. I have been testing with better hardware and the problem has gone. Closing this issue. Thanks @damongolding
